/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opdar_unqlite_UnqliteDatabase */

#ifndef _Unqlite_Cursor
#define _Unqlite_Cursor

#include <string.h>
#include <jni.h>
#include <android/log.h>
#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, "Unqlite-Android", __VA_ARGS__)
unqlite *pDb;
int rc;
unqlite_kv_cursor *pCursor;

#endif
